apiVersion: v1
kind: Pod
metadata:
  name: testpod4324325
spec:
  schedulerName: my-scheduler
  containers:
  - name: nginx
    image: perl
    command: ["sleep",  "600"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
    ports:
    - containerPort: 80
  restartPolicy: Never
