apiVersion: v1
kind: Pod
metadata:
  name: test-high-resource-consumption
spec:
  schedulerName: my-scheduler
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "1000m"
    ports:
    - containerPort: 80
