apiVersion: v1
kind: Pod
metadata:
  name: test-pod-two
  labels:
    realtime: not-critical
spec:
  schedulerName: my-scheduler
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 81
