apiVersion: v1
kind: Pod
metadata:
  name: NAME_LABEL
spec:
  schedulerName: my-scheduler
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
    ports:
    - containerPort: 80
